# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: UseDotNet@2
  displayName: Install DotNet SDK
  inputs:
    packageType: 'sdk'
    version: '5.x'
    includePreviewVersions: false


- task: DotNetCoreCLI@2
  displayName: 'restore nugets'
  inputs:
    command: 'restore'
    projects: '**/*BlazorFluentUI.sln'
    feedsToUse: 'select'

- task: DotNetCoreCLI@2
  displayName: 'Build Solution'
  inputs:
    command: 'build'
    projects: '**/*BlazorFluentUI.sln'
    arguments: '-c Release --no-restore'

- task: DotNetCoreCLI@2
  displayName: 'Create NuGet package'
  inputs:
    command: 'pack'
    packagesToPack: '**/*.csproj;!**/BlazorFluentUI.Demo.*.csproj'
    versioningScheme: 'byPrereleaseNumber'
    majorVersion: '4'
    minorVersion: '0'
    patchVersion: '0'

- task: DotNetCoreCLI@2
  displayName: 'Push NuGet Packages'
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/*.nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: '5355f597-190a-4424-83da-cd89cd362a24/62e4a3d2-c255-43ac-a465-30d8f5f041e1'

