# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
   branches:
     exclude:
       - '*'

pr:
 branches:
    exclude:
      - '*'

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: UseDotNet@2
  displayName: Install DotNet SDK
  inputs:
    packageType: 'sdk'
    version: '5.x'
    includePreviewVersions: false


- task: DotNetCoreCLI@2
  displayName: 'restore nugets'
  inputs:
    command: 'restore'
    projects: '**/*FluentUI.sln'
    feedsToUse: 'select'

- task: DotNetCoreCLI@2
  displayName: 'Build Solution'
  inputs:
    command: 'build'
    projects: '**/*FluentUI.sln'
    arguments: '-c Release --no-restore'

- task: DotNetCoreCLI@2
  displayName: 'Create NuGet package'
  inputs:
    command: 'pack'
    packagesToPack: '**/*.csproj;!**/FluentUI.Demo.*.csproj'
    versioningScheme: 'byEnvVar'
    versionEnvVar: 'Version'

- task: NuGetCommand@2
  displayName: 'Push NuGet Packages'
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/*.nupkg'
    nuGetFeedType: 'external'
    publishFeedCredentials: 'Nuget-FluentUI'
    includeNuGetOrg: true
    feedsToUse: select
    
